### ISSUE TITLE
Add Gist management view

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/gist-fs#11]
In addition to allowing you to list your gists via #2, we should also add a tree view to easily manage your Gists visually (add/delete/open/star).

**Comment by IlanVivanco** [comment]
Great idea!

**Comment by lostintangent** [comment]
Just shipped an update to the marketplace that includes a new `Gists` view on the `Explorer` tab. Would love to hear folk's feedback!

<img src="https://user-images.githubusercontent.com/116461/69767270-4d3a7300-1130-11ea-9785-fc88c5dda79c.png" width="300px"/>

**Comment by IlanVivanco** [comment]
Love it! 
Although if I need to be picky, it would even greater if this could have its own tab, wouldn't it?

**Comment by lostintangent** [comment]
Sounds good, I’ll make it a distinct tab as well and ship that in the next update (today or tomorrow).

**Comment by lostintangent** [comment]
@IlanVivanco FYI, I shipped an update that adds a new activity bar tab 👍 Let me know if you have any more feedback!

**Comment by IlanVivanco** [comment]
This is awesome! It worked like a charm!

I love the new name BTW. 🚀

**Comment by lostintangent** [comment]
@IlanVivanco Thanks!
