### ISSUE TITLE
Allow opening/creating a Gist within the current workspace

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/gist-fs#12]
Currently, when you create/open a Gist, we open it as a new virtual workspace. This reloads VS Code, and prevents you from being able to easily work on a Gist alongside of another project. To address this, we should add an option to open/create a Gist as a series of “loose files”’within the current VS Code instance (without needing to reload).

**Comment by IlanVivanco** [comment]
+1 on this! This could be implemented as a new the sidebar

**Comment by lostintangent** [comment]
This has now been implemented via an overhaul of the `GistFS: Open Gist` command.
