### ISSUE TITLE
Allow listing your Gists

### ISSUE THREAD

**Issue by lostintangent** [vsls-contrib/gist-fs#2]
Instead of just creating a new gist, or opening one by ID, we should add a command to allow users to view all of their current Gists and then open one. That way, you don’t need to retrieve the Gist ID from the browser before you can begin editing it in VS Code.

**Comment by ljtill** [comment]
+1 : The ability to browse all Gists would be superb!

**Comment by lostintangent** [comment]
@ljtill I’ll be adding that this week, so stay tuned 👍

**Comment by ljtill** [comment]
> @ljtill I’ll be adding that this week, so stay tuned 👍

Excellent, thanks @lostintangent!

**Comment by khuongduybui** [comment]
You know what? I think this should be listed in a panel within `Remote Explorer` pane.
(To be absolutely clear, I mean the Remote Explorer pane that current lists SSH, Docker, WSL, and VS Online targets)
