### ISSUE TITLE
Wish: Improve README on the installation part

### ISSUE THREAD

**Issue by stangri** [vsls-contrib/gist-fs#6]
Couldn't find the gistfs (nor gist-fs) extension on the marketplace on the following version, please elaborate how this extension can be installed. When searching for just "gist" a few options come up, but judging by the extension authors, neither of them is this extension.

```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.69-06666-g6c4f8cbba24e
```

**Comment by lostintangent** [comment]
@stangri Apologies! I hadn't published the extension to the marketplace yet, but it's available now. Grab it [here](https://aka.ms/gist-fs) or search for `GistFS` in VS Code.
