### ISSUE TITLE
Allow creating secret Gists

### ISSUE THREAD

**Issue by enozero** [vsls-contrib/gist-fs#8]
Gists can be either public or secret. Many times, I want to create a secret Gist. It would be great if there was a command to create a secret Gist.

**Comment by lostintangent** [comment]
Hey! When you run the `GistFS: New Gist` command, it will ask you if you want to create a public or secret gist (after asking you the name of the starting file for the gist)? Is this along the lines of what you're thinking? Maybe to make it more ergonomic, I could add a `GistFS: New Secret Gist`, which simply ran the `GistFS: New Gist` command, but didn't ask whether you wanted public/secret gist or not?

**Comment by enozero** [comment]
I like the second option: add a `GistFS: New Secret Gist` command. That one makes it clear the intention from the beginning, and most people know up front whether it would be secret or public.

**Comment by lostintangent** [comment]
Sounds good! I’ll implement this tonight 👍

**Comment by lostintangent** [comment]
Just published an update to the market that introduces two separate commands: `GistFS: New Gist (Public)` and `GistFS: New Gist (Secret)`. Let me know if you have any further feedback. Thanks!
